# SPDX-License-Identifier: GPL-2.0
#
# Xiaomi for misc devices.
#

obj-$(CONFIG_XIAOMI_HWID) += hwid/

obj-$(CONFIG_MIEV) += miev/

obj-$(CONFIG_MI_WIFI_GPIO) += wifi_gpio/

obj-$(CONFIG_BUILD_PRODUCT_NAME) += build_product_name/

obj-$(CONFIG_MI_T1_CHIP) += mi_t1_chip/

obj-$(CONFIG_MI_LOCKING)   += mi_locking/

obj-$(CONFIG_CAM_INTENTAWARE_FSYS) += cam_intentaware_fsys/

obj-$(CONFIG_XIAOMI_DEBUG_EXT) += debug_ext/

obj-$(CONFIG_XIAOMI_PERF_HELPER) += perf_helper/

obj-$(CONFIG_XIAOMI_MI_MEMORY) += mi_memory/
